import './globals.css';

export const metadata = {
  title: 'Telemedicine App',
  description: 'Generated by create next app',
  keywords: 'Next.js, SEO, Web Development, React, JavaScript',
  author: 'Faizal / Murali ',
  robots: 'index, follow',
  charset: 'UTF-8',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <head>
        <meta charSet={metadata.charset} />
        <meta name="description" content={metadata.description} />
        <meta name="keywords" content={metadata.keywords} />
        <meta name="author" content={metadata.author} />
        <meta name="robots" content={metadata.robots} />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Space+Grotesk:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <title>{metadata.title}</title>
      </head>
      <body className="h-full bg-gray-900">
        {children}
      </body>
    </html>
  );
}
